### PR TITLE
Dockerizing and Running Metrics app on Kubernetes

### PR DESCRIPTION
**Pull request by pranavcode**
Configures the project to run on k8s infrastructure.

Sub tasks:
- [x] Get go-metrics binary running locally inside a container
- [x] Dockerize go-metrics application	
- [x] Get go-metrics app running on Codeship CI env
- [x] Deploy go-metrics app on Google Kubernetes cluster along side other related apps/services
- [x] Code clean-up and refactoring

This change is [Reviewable](https://reviewable.io/reviews/replaygaming/go-metrics/1)

### CODE REVIEW

**Comment by Draiken** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[deployment.yaml, line 18 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK884rsdyWNHoLv_41I:-KK884rtdYk83lLUSIhq:-1362271363) ([raw file](https://github.com/replaygaming/go-metrics/blob/3a0df29eec192830cb9a518cb042e7ec5e3637c5/deployment.yaml#L18)):*
> ```YAML
>         - name: METRICS_USER
>           valueFrom:
>             secretKeyRef:
> ```

You created the secret with all keys already?

---

*[Dockerfile.build.dev, line 1 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK88VTh-Se50ANlhk9S:-KK88VTh-Se50ANlhk9T:188199176) ([raw file](https://github.com/replaygaming/go-metrics/blob/3a0df29eec192830cb9a518cb042e7ec5e3637c5/Dockerfile.build.dev#L1)):*
> ```
> FROM alpine:3.2
> ```

Why do you need a specific dev build?
If you want to run this locally, either use it on kubernetes or run the dist image built by jet. If your setup is correct, it should work as expected

---

*[main.go, line 20 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK890CspJr83h_bkU2A:-KK890CspJr83h_bkU2B:1987505997) ([raw file](https://github.com/replaygaming/go-metrics/blob/bd0d88d0ba996d249e998ca46aa5cfb36851d080/main.go#L20)):*
> ```Go
> }
> 
> func main() {
> ```

Why do we need to remove the flags?
Flags already have a "default" parameter, you can just use it to get the parameters from ENV in case CLI flags are not provided.

This keeps the program flexible, instead of forcing you to always use ENV vars :smiley: 

---

*[main.go, line 26 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK89yE_MbvHmSk8FsKH:-KK89yE_MbvHmSk8FsKI:2139589638) ([raw file](https://github.com/replaygaming/go-metrics/blob/3a0df29eec192830cb9a518cb042e7ec5e3637c5/main.go#L26)):*
> ```Go
> 
> func warn(message string, err error) {
> 	logger.Printf("[WARN] %s: %s", message, err)
> ```

Go logger doesn't include a "warning" format already?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1)*

**Comment by d-Pixie** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[main.go, line 20 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK890CspJr83h_bkU2A:-KK8ZZI7csaC6p43FbtH:1092789843) ([raw file](https://github.com/replaygaming/go-metrics/blob/bd0d88d0ba996d249e998ca46aa5cfb36851d080/main.go#L20)):*
<details><summary><i>Previously, Draiken (Luiz Felipe G. Pereira) wrote…</i></summary>
> Why do we need to remove the flags?
> Flags already have a "default" parameter, you can just use it to get the parameters from ENV in case CLI flags are not provided.
> 
> This keeps the program flexible, instead of forcing you to always use ENV vars :smiley: 
</details>
Don't agree; Flexibility = more code = more maintenance. If we don't know we need it we shouldn't maintain it "just in case". The infrastructure this is expected to run on, local, staging and production all will use ENV vars for this so no need to keep CLI options around IMO.

---

*[main.go, line 26 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK89yE_MbvHmSk8FsKH:-KK8_kLgrYI7X2HvuKBi:-557459448) ([raw file](https://github.com/replaygaming/go-metrics/blob/3a0df29eec192830cb9a518cb042e7ec5e3637c5/main.go#L26)):*
<details><summary><i>Previously, Draiken (Luiz Felipe G. Pereira) wrote…</i></summary>
> Go logger doesn't include a "warning" format already?
</details>
No https://golang.org/pkg/log/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1)*

**Comment by pranavcode** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[deployment.yaml, line 18 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK884rsdyWNHoLv_41I:-KKCsg8QeBHK5NbWhxCr:1332003319) ([raw file](https://github.com/replaygaming/go-metrics/blob/3a0df29eec192830cb9a518cb042e7ec5e3637c5/deployment.yaml#L18)):*
<details><summary><i>Previously, Draiken (Luiz Felipe G. Pereira) wrote…</i></summary>
> You created the secret with all keys already?
</details>
That was because I had planned for the secrets already and were mostly referred from eventsource k8s deployment config project. You are right, I reached the secret creation process only when I started deploying to k8s cluster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1)*

**Comment by pranavcode** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Dockerfile.build.dev, line 1 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK88VTh-Se50ANlhk9S:-KKCtGakX8s3i8uA582G:-130101505) ([raw file](https://github.com/replaygaming/go-metrics/blob/3a0df29eec192830cb9a518cb042e7ec5e3637c5/Dockerfile.build.dev#L1)):*
<details><summary><i>Previously, Draiken (Luiz Felipe G. Pereira) wrote…</i></summary>
> Why do you need a specific dev build?
> If you want to run this locally, either use it on kubernetes or run the dist image built by jet. If your setup is correct, it should work as expected
</details>
This was added when I was trying to run the built app locally pointing to local docker container. Having two docker files, viz build and dist, similar to codeship docker files, I felt it was little tedious to have all configuration related to moving binaries from one container to other. So, created a single docker file to achieve both operations to start of.

I agree, it should not be part of this repo anymore, as it was related to my experimental work on local box. Jet built images also works fine once I have registry setup locally for k8s (https://github.com/kubernetes/kubernetes/issues/1293). Which I thought would be lengthy process as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1)*

**Comment by pranavcode** [comment]
@replaygaming/developers Please review!

---

Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-:-KKCwhqhG1klBnOYsI1z:1903440492)*

**Comment by Draiken** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[deployment.yaml, line 18 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK884rsdyWNHoLv_41I:-KKDI0z76UoUKhCPRKQR:-1824837790) ([raw file](https://github.com/replaygaming/go-metrics/blob/3a0df29eec192830cb9a518cb042e7ec5e3637c5/deployment.yaml#L18)):*
<details><summary><i>Previously, pranavcode (Pranav Kulkarni) wrote…</i></summary>
> That was because I had planned for the secrets already and were mostly referred from eventsource k8s deployment config project. You are right, I reached the secret creation process only when I started deploying to k8s cluster.
</details>
That's fine. It's good that we already use secrets on this, they're pretty simple to use

---

*[main.go, line 20 \[r1\]](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-KK890CspJr83h_bkU2A:-KKDIP1QHnjUsZwAN-28:-967575566) ([raw file](https://github.com/replaygaming/go-metrics/blob/bd0d88d0ba996d249e998ca46aa5cfb36851d080/main.go#L20)):*
<details><summary><i>Previously, d-Pixie (Jonas Schubert Erlandsson) wrote…</i></summary>
> Don't agree; Flexibility = more code = more maintenance. If we don't know we need it we shouldn't maintain it "just in case". The infrastructure this is expected to run on, local, staging and production all will use ENV vars for this so no need to keep CLI options around IMO.
</details>
I'd agree if this was some kind of big complex code, which is not the case. By changing from CLI args to ENV, he had to change the code, change the docs and made it harder to for example, run this locally. There is no greater cost on maintaining that. In fact there would be even less changes if we just added ENV support as the default values for the CLI args.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-:-KKDJzGHRyZhMs9lNR6D:1417088721)*

**Comment by Draiken** [comment]
I suggest you take the current master, create a legacy branch with it, and merge this into it.
Unlike the main RP repo, we don't deploy this... ever

@replaygaming/developers what do you guys think?

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-:-KKhVHCCW5V2RDtcAgYK:-141893055)*

**Comment by pranavcode** [comment]
I agree, will merge it into a separate branch and close this PR.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/replaygaming/go-metrics/1#-:-KKrGp4vAEuM-Pj8LydM:908362424)*

**Comment by pranavcode** [comment]
Closing this PR in the interest of changing target branch from **`master`** to **`kubernetes/master`**.
Please refer: PR https://github.com/replaygaming/go-metrics/pull/2.

**Pull request closed without merging**
